# Copyright (C) 2016-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# - name: Setup Docker to version {{ docker_version }} (the latest supported by Kubernetes)
#   template: src=docker-apt-pin.txt dest=/etc/apt/preferences.d/docker

- name: Install docker
  apt:
    state: present
    # name: docker-ce={{ docker_version }}
    # autoremove: yes
    # force: yes

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable

- name: Install Docker
  apt: name=docker-ce

- name: Creates Docker systemd configuration directory
  action: file path=/etc/systemd/system/docker.service.d state=directory owner=root group=root recurse=yes

- name: Install Docker customization
  copy: src=overlay.conf dest=/etc/systemd/system/docker.service.d/overlay.conf
  notify:
    - reload systemd

- name: Enable and restart Docker engine
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
