kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alertmanager-pvc-claim
spec:
  # storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc-claim
spec:
  # storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
