# Copyright (C) 2016, 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    k8s-app: kube-scheduler-monitor
    prometheus: main
  name: kube-scheduler-monitor
spec:
  groups:
    - name: kube-scheduler.rules
      rules:
        - record: cluster:scheduler_e2e_scheduling_latency_seconds:quantile
          expr:
            histogram_quantile(0.99, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.99"
        - record: cluster:scheduler_e2e_scheduling_latency_seconds:quantile
          expr:
            histogram_quantile(0.9, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.9"
        - record: cluster:scheduler_e2e_scheduling_latency_seconds:quantile
          expr:
            histogram_quantile(0.5, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.5"
        - record: cluster:scheduler_scheduling_algorithm_latency_seconds:quantile
          expr:
            histogram_quantile(0.99, sum(scheduler_scheduling_algorithm_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.99"
        - record: cluster:scheduler_scheduling_algorithm_latency_seconds:quantile
          expr:
            histogram_quantile(0.9, sum(scheduler_scheduling_algorithm_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.9"
        - record: cluster:scheduler_scheduling_algorithm_latency_seconds:quantile
          expr:
            histogram_quantile(0.5, sum(scheduler_scheduling_algorithm_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.5"
        - record: cluster:scheduler_binding_latency_seconds:quantile
          expr:
            histogram_quantile(0.99, sum(scheduler_binding_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.99"
        - record: cluster:scheduler_binding_latency_seconds:quantile
          expr:
            histogram_quantile(0.9, sum(scheduler_binding_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.9"
        - record: cluster:scheduler_binding_latency_seconds:quantile
          expr:
            histogram_quantile(0.5, sum(scheduler_binding_latency_microseconds_bucket)
            BY (le, cluster)) / 1e+06
          labels:
            quantile: "0.5"
        - alert: K8SSchedulerDown
          expr: absent(up{job="kube-scheduler"} == 1)
          for: 5m
          labels:
            severity: critical
          annotations:
            description:
              There is no running K8S scheduler. New pods are not being assigned
              to nodes.
            runbook: https://coreos.com/tectonic/docs/latest/troubleshooting/controller-recovery.html#recovering-a-scheduler
            summary: Scheduler is down
