---
- name: install defined version of Home Assistant
  pip:
    name=homeassistant
    virtualenv=/srv/hass
    version="{{ ha_version }}"
    executable=pip3
  when: ha_version is defined

- name: install latest version of Home Assistant
  pip: 
    name=homeassistant
    extra_args="--upgrade" 
    executable=pip3
  when: ha_version is undefined

