---
- name: Install Python and tools
  package: name={{ item }} state=present
  with_items:
  - python3
  - python3-pip
  - python3-dev
  - python3-setuptools
  - gcc

- name: Install virtualenv
  pip:
    name=virtualenv
    state=latest
    executable=pip3

# - name: Create user for home assistant
#  user:
#    name: hass
#    groups: dialout
#    system: yes

- name: Create hass directory
  file:
    path: /srv/hass
    state: directory
    mode: 0755
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
  become: yes
  become_user: root

