---
- name: Configure systemd unit file
  template:
    src: 'etc/systemd/system/home-assistant.service.j2'
    dest: '/etc/systemd/system/home-assistant.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: homeassistant__register_systemd_unit_file

- name: just force systemd to reread configs
  systemd:
    name: 'home-assistant'
    daemon_reload: 'yes'

- name: Set Home Assistant state using systemd
  systemd:
    name: 'home-assistant'
    state: 'started'
    enabled: True
    masked: False
    daemon_reload: '{{ homeassistant__register_systemd_unit_file|changed }}'
