---
route:
  group_by: [cluster, alertname]
  group_interval: 2m
  group_wait: 1m #wait a minute for other alert before sending
  repeat_interval: 720h #wait a month before resending alert
  # If an alert isn't caught by a route, send it slack.
  receiver: slack_alert_manager
  routes:
   # Send severity=slack alerts to slack.
   - match:
       severity: low
     receiver: slack_alert_manager_informations
   - match:
       severity: medium
     receiver: slack_alert_manager_informations
   - match:
       severity: critical
     receiver: slack_alert_manager

receivers:
- name: slack_alert_manager
  slack_configs:
  - api_url: "https://hooks.slack.com/services/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"
    username: "Jarvis Alert"
    #color: "warning"
    channel: '#alert'
    title: "HIGH - {{ .CommonLabels.alertname }}"
    text: "Hello,\n\n{{ range .Alerts }}- {{ .Annotations.summary }}\n{{ end }}\n"
    send_resolved: true
- name: slack_alert_manager_informations
  slack_configs:
  - api_url: "https://hooks.slack.com/services/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"
    username: "Jarvis Alert"
    #color: "warning"
    channel: '#notifications'
    title: "MEDIUM - {{ .CommonLabels.alertname }}"
    text: "Hello,\n\n{{ range .Alerts }}- {{ .Annotations.summary }}\n{{ end }}\n"
    send_resolved: true

