# Copyright (C/p 2016-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluentbit
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/component: log
    app.kubernetes.io/part-of: jarvis
    app.kubernetes.io/managed-by: kubectl
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentbit
        app.kubernetes.io/instance: fluentbit
        app.kubernetes.io/version: "v1"
        app.kubernetes.io/component: log
        app.kubernetes.io/part-of: jarvis
        app.kubernetes.io/managed-by: kubectl
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      serviceAccountName: fluentbit
      containers:
      - name: fluent-bit
        image: hannahsfamily/fluent-bit:1.2.0-arm64v8
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentbit-config
          mountPath: /fluent-bit/etc/
        resources:
          limits:
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentbit-config
        configMap:
          name: fluentbit
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   operator: Exists
      #   effect: NoSchedule
      # - operator: "Exists"
      #   effect: "NoExecute"
      # - operator: "Exists"
      #   effect: "NoSchedule"
