# Copyright (C) 2016, 2017 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Reset Kubernetes
  command: /usr/bin/kubeadm reset

- name: Check kubelet state
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started

- debug:
    msg: "Kubernetes token: {{ hostvars[groups['master'][0]].kubeadm_token }}"

- name: Adding node to cluster
  shell: "kubeadm join --token {{ hostvars[groups['master'][0]].kubeadm_token }} {{ groups['master'][0] }}:6443 --skip-preflight-checks"
  register: k8s_join_output

- debug: msg="{{ k8s_join_output.stdout }}"
