# Copyright (C) 2016, 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: node-exporter
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: node-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: node-exporter
          image: "quay.io/prometheus/node-exporter:latest"
          args:
          - --no-collector.filesystem
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
          ports:
            - name: metrics
              containerPort: 9100
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /host/proc
              name: proc-fs
            - mountPath: /host/sys
              name: sys-fs
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "75Mi"
              cpu: "20m"
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc-fs
          hostPath:
            path: /proc
        - name: sys-fs
          hostPath:
            path: /sys
