# Copyright 2016-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    k8s-app: prometheus
    prometheus: cluster
  name: prometheus
spec:
  serviceAccountName: prometheus
  baseImage: "quay.io/prometheus/prometheus"
  version: "v2.11.1"
  ports:
  - name: web
    containerPort: 9090
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager
        port: http
  paused: false
  replicas: 1
  logLevel: info
  routePrefix: "/"
  serviceMonitorNamespaceSelector: {} # auto discover all service monitors accross all namespaces
  # serviceMonitorSelector: {} # auto discover all service monitors in namespaces configured one line above
  serviceMonitorSelector:
    matchLabels:
      prometheus: cluster
    # matchExpressions:
    # - key: promethus
    #   operator: In
    #   values:
    #     - cluster
  ruleSelector:
    matchLabels:
      prometheus: cluster
  ruleNamespaceSelector: {}
  resources:
    requests:
      memory: 200Mi
      cpu: 150m
    limits:
      memory: 250Mi
      cpu: 200m
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       accessModes:
  #       - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 10Gi
  #       storageClassName: jarvis-nfs-client
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: prometheus
                operator: In
                values:
                - cluster
          topologyKey: "failure-domain.beta.kubernetes.io/zone"

