kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc-claim-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "jarvis-nfs-client"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc-claim-config
  annotations:
    volume.beta.kubernetes.io/storage-class: "jarvis-nfs-client"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
