apiVersion: v1
kind: Service
metadata:
  labels:
    provider: jarvis
  name: grafana
spec:
  ports:
  - name: grafana
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
