- name: Reset Kubernetes installation
  shell: "kubeadm reset"
  when: "reset==true"

- name: Initialize Kubernetes cluster for ARM 
  shell: "kubeadm init --kubernetes-version {{k8s_release}} --apiserver-advertise-address={{api_server_ip}} --token {{token}} --pod-network-cidr={{cidr}} --skip-preflight-checks"

- name: Install Networking: Weave
  shell: "kubectl apply -n kube-system -f \"https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')\""
  register: out

- name: Install Kubernetes Dashboard
  shell: curl -sSL 'https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml' | sed 's/amd64/{{arch}}/g' | kubectl create -f -

- debug: var=out.stdout_lines  

