apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: unsee
    provider: jarvis
  name: unsee
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    name: unsee
  type: ClusterIP
